name: my_CI_workflow
env:
  VAR_1      : 12
  var2       : "text_var1"
  SHA_COMMIT : "deploy_ver: ${{github.sha}}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Echo
        run: echo "Hi there!!!"
        
      - name: Execute some commands   
        run: |
          echo "There are env variables"
          echo "VAR_1: ${{env.VAR_1}}"
          echo "SHA_COMMIT: ${{env.SHA_COMMIT}}"

          
              
        
