name: my_CI_workflow
env:
  VAR_1      : 12
  var2       : "text_var1"
  SHA_COMMIT : "deploy_ver: ${{github.sha}}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build1:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        run: echo "Hi there!!!"

     
  deploy:
    runs-on: ubuntu-latest
    needs: [build1]
    steps:
      - name: Echo
        run: echo "Hi there!!!"
        
      - name: Execute some commands   
        run: |
          echo "There are env variables"
          echo "VAR_1: ${{env.VAR_1}}"
          echo "SHA_COMMIT: ${{env.SHA_COMMIT}}"
          echo "secret1 : ${{ secrets.SECRET_1 }}"
          echo "secret1 : ${{ my_env.SECRET_1 }}"
          

          
              
        
